### ISSUE TITLE
调整背景透明度后编辑区文字也会变化，难以看清

### ISSUE THREAD

**Issue by Ming-mingjiu** [HowcanoeWang/siyuan-plugin-background-cover#1]
另有个想法，可不可以直接调整透明度，让他呈现出电脑桌面下一个窗口的样子？

**Comment by HowcanoeWang** [comment]
完全仿照vscode那个插件的做法来搞的，建议透明度数值不要超过0.3体验比较好

之前一版用的方法是直接修改CSS的alpha值来实现的，好处就是不会改变文字和内容的透明度，但是需要一个个主题适配工作量太大了而且会污染CSS（如果需要可以考虑增加一个开关，让用户选择是整体透明度改变还是css透明度改变？）

> 让他呈现出电脑桌面下一个窗口的样子？

这句话没看太懂，能再仔细解释一下吗

**Comment by HowcanoeWang** [comment]
以及还有可能跟主题和用的图片有关系，用的是列表中列出的目前适配的主题吗

**Comment by Ming-mingjiu** [comment]
> 

![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/130682753/29ace3ac-549a-45e6-a320-0fe76aec3318)
类似obsidian里面有个半透明效果，打开之后，他呈现的高斯模糊图片，实际是我电脑桌面的背景，因为电脑下一层窗口就是桌面
![wallhaven-we628p](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/130682753/6de6c6ad-cd82-40d8-bf46-ebf5de852aad)

**Comment by Ming-mingjiu** [comment]
![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/130682753/67ff54c7-4f1a-4f05-b563-2cf46104781d)
我现在体验该插件用的是任我行主题，可以看出纯黑文字部分已经有点开始发灰，不过整体效果，我觉得比savor要好看所以，我就接着用这个主题了

> 以及还有可能跟主题和用的图片有关系，用的是列表中列出的目前适配的主题吗(默认和Savor应该都还行)

**Comment by HowcanoeWang** [comment]
背景虚化可以研究研究。

然后文字看不清应该是主题的适配问题，抽空去适配一下这个主题

**Comment by HowcanoeWang** [comment]
适配之后大概是这样的效果，下一版发布更新

![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/19968935/00d95ec2-a6fe-4fcc-abb3-35f6bed665ca)

**Comment by HowcanoeWang** [comment]
背景图片的毛玻璃效果实现，后续更新

![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/19968935/0e06159a-abad-4100-add9-a383865b5a0e)

**Comment by HowcanoeWang** [comment]
close on 30d93226ea32fec75e311dbaa2680045e03d36a3
