### ISSUE TITLE
使用原版主题依旧会导致关系图的顶栏被遮挡，切换到css的部分透明会解决这个问题

### ISSUE THREAD

**Issue by Hai-de** [HowcanoeWang/siyuan-plugin-background-cover#10]

**Comment by HowcanoeWang** [comment]
![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/19968935/9053ff47-6c3c-4b9f-bd04-70713f778df1)

有截图说明一下吗，我这边好像是正常的

**Comment by Hai-de** [comment]
抱歉，我忘了说这是在打开了关系图的全屏
下面分别是全局透明和css透明的效果
<img width="1453" alt="屏幕截图 2023-08-08 000606" src="https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/69635508/624a8282-f409-4820-a5e1-5feb6e214e16">
————————

<img width="1380" alt="屏幕截图 2023-08-08 000628" src="https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/69635508/6b2823dd-1455-4072-8a15-2a71b5566293">

**Comment by Hai-de** [comment]
> ![image](https://user-images.githubusercontent.com/19968935/258568068-9053ff47-6c3c-4b9f-bd04-70713f778df1.png)
> 
> 有截图说明一下吗，我这边好像是正常的

抱歉，我忘了说这是在打开了关系图的全屏
下面分别是全局透明和css透明的效果
<img width="1453" alt="屏幕截图 2023-08-08 000606" src="https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/69635508/3280613a-04a2-4ce8-a155-ce4f65f6099d">
——————

<img width="1380" alt="屏幕截图 2023-08-08 000628" src="https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/69635508/9d4c2982-d862-4cbc-823d-592508a49e48">

**Comment by HowcanoeWang** [comment]
已经定位问题是 全局模式中的z-index顺序的问题(添加opacity会修改元素的z-index值，导致元素的层级顺序有问题)，后续看看应该如何调整

**Comment by HowcanoeWang** [comment]
弃用css模式，改用body opacity 解决所有主题适配问题

e27ece7d627616d292b56884dd3ee1158bd298ce
