### ISSUE TITLE
打开思源笔记后无法正常加载背景图片

### ISSUE THREAD

**Issue by fenshen000** [HowcanoeWang/siyuan-plugin-background-cover#11]
- 已更新至最新版
- 启动思源笔记后，背景图片无法自动加载，必须手动`关闭图片背景`再重新`打开图片背景`，图片才能正常加载出来
- 使用的主题是`Savor`，在官方默认主题下同样也会出现这个问题

**Comment by HowcanoeWang** [comment]
Windows端？

**Comment by HowcanoeWang** [comment]
目前看下来，发现一开始加载有点卡，等一等然后看看能不能自动加载出来？

**Comment by HowcanoeWang** [comment]
已定位原因，是新用的获取已安装主题的API时间卡顿

![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/19968935/dcdcb3d6-19c8-4c0f-b2d1-63ce9e16b410)

后续会把这一部后置，让图片先加载出来

**Comment by fenshen000** [comment]
> 目前看下来，发现一开始加载有点卡，等一等然后看看能不能自动加载出来？
win端，不过我这里是完全加载不出来的样子，只能手动给刷新出来

**Comment by fenshen000** [comment]
> 已定位原因，是新用的获取已安装主题的API时间卡顿
> 
> ![image](https://user-images.githubusercontent.com/19968935/260766164-dcdcb3d6-19c8-4c0f-b2d1-63ce9e16b410.png)
> 
> 后续会把这一部后置，让图片先加载出来

好的！好快啊

大佬早点休息~
