### ISSUE TITLE
获取最新主题信息失败

### ISSUE THREAD

**Issue by xuguangjian** [HowcanoeWang/siyuan-plugin-background-cover#12]
每次刷新思源都会出现这个提示
![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/66892415/7471a911-89bb-433f-a1f2-584b928d0b26)

**Comment by HowcanoeWang** [comment]
因为你安装了新主题，然后缓存里面没有主题对应的中文名，就会尝试从github上下载最新的，然后github连不上就会出现这个问题

**Comment by xuguangjian** [comment]
那我把其他的主题卸载掉只留默认的是不是就没有问题了？

**Comment by xuguangjian** [comment]
没有问题了，我全部卸载了，不报错了


| |
许广健
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年9月9日 13:23 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [HowcanoeWang/siyuan-plugin-background-cover] 获取最新主题信息失败 (Issue #12) |

因为你安装了新主题，然后缓存里面没有主题对应的中文名，就会尝试从github上下载最新的，然后github连不上就会出现这个问题

**Comment by xuguangjian** [comment]
没问题了，就是主题有问题，

**Comment by HowcanoeWang** [comment]
不需要把所有的主题都卸载了，基本上下那些下载量比较大的主题就没问题
