### ISSUE TITLE
savor主题下失去焦点后标题栏虚化失效问题

### ISSUE THREAD

**Issue by zihaoliao** [HowcanoeWang/siyuan-plugin-background-cover#13]
- 平台：win10
- 思源版本：v2.10.4
- savor主题版本：v3.5.10
- 插件版本：v0.4.5
- 问题描述：正常在思源软件中进行输入没有问题，但将鼠标移至其他应用时，会导致标题栏虚化失效，出现高亮现象。
- 问题截图：
这张是光标焦点在思源软件中的情况
![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/7894966/3d737e13-02d5-48a8-920c-96eb0a324a0c)
这张是光标焦点在谷歌浏览器中的情况
![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/7894966/86018921-6949-4597-9364-a83d13f6c490)

**Comment by HowcanoeWang** [comment]
主题没有适配的问题，建议联系主题作者，可以试试savor主题看看适配后的效果

**Comment by HowcanoeWang** [comment]
感觉像是之前的缓存没有刷新的问题，我这边更新后没法复现，重启看看？

**Comment by zihaoliao** [comment]
我分别重启了思源和笔记本，均稳定出现虚化失效问题。不清楚是哪里没有适配上，大佬需要什么日志之类的吗？
![siyuan_problem](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/7894966/e9a8974b-a530-411a-a779-a53f6bdcce9e)

**Comment by HowcanoeWang** [comment]
有可能是思源2.10.4更新了样式，建议在 savor主题下反馈，更改这个不在背景插件的功能里面

https://github.com/royc01/notion-theme
