### ISSUE TITLE
从Github上获取最新主题信息themes.json'失败，使用插件自身的缓存信息

### ISSUE THREAD

**Issue by AvoidantPerDis** [HowcanoeWang/siyuan-plugin-background-cover#15]
在使用安卓端，思源伺服浏览器desktop端时候会出现
![Screenshot_2024-02-07-22-24-38-172_mark via](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/154863885/dfc524e2-c4e6-46d7-8858-fa3805516e84)
并且安卓端与PC端同步的时候，会有偶发的丢失图片现象，不知道是否与这个bug相关

**Comment by AvoidantPerDis** [comment]
我自身的网络是可以直连github的

**Comment by AvoidantPerDis** [comment]
屏蔽功能确实用不上，主要这个每次打开都有比较烦，如果屏蔽功能关闭/没有开启任何一个主题屏蔽的话，能不能关掉提示？

**Comment by HowcanoeWang** [comment]
使用了theme.json里没有包含的新皮肤，触发了拉取新皮肤缓存的功能，比较简单去除的方法是，卸载新皮肤用默认的。

或者手动从官方模板  下载theme.json,替换到背景插件路径src/theme.json

**Comment by AvoidantPerDis** [comment]
我试试

**Comment by AvoidantPerDis** [comment]
我替换了 theme.json 还是会报错 而且我的主题是任我行主题
![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/154863885/130314d5-e9f7-4714-beee-c7ea3b1c7f9d)

**Comment by AvoidantPerDis** [comment]
安卓端背景插件路径下没有src文件夹

**Comment by AvoidantPerDis** [comment]
我把移动端删到只剩一个皮肤好像就可以了

**Comment by HowcanoeWang** [comment]
> 我把移动端删到只剩一个皮肤好像就可以了

对，他会遍历所有安装的皮肤
