### ISSUE TITLE
背景图漏光

### ISSUE THREAD

**Issue by Bluewaterhua** [HowcanoeWang/siyuan-plugin-background-cover#20]
<img width="492" alt="image" src="https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/47163968/0dab58cd-c282-4117-b04a-5b73fc194af4">
背景图和整个siyuan不匹配 有点漏光

**Comment by HowcanoeWang** [comment]
大概率是主题的问题。。。

**Comment by Bluewaterhua** [comment]
我看了下确实是savor的问题。。。。。。乌龙
