### ISSUE TITLE
每次重启思源笔记和更换主题，图片失效

### ISSUE THREAD

**Issue by MystiKun** [HowcanoeWang/siyuan-plugin-background-cover#4]
重启思源笔记/更换主题 图片失效，提示图片不符合缓存的命名规则
![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/78802888/4f9cdd3d-c5f4-491d-b2e6-59a975ee8b4c)

每次重启软件都要重新刷新缓存，再次添加图片，很麻烦
插件版本： 0.3.0
思源笔记版本 2.9.2
系统版本 Win11 22H2

**Comment by HowcanoeWang** [comment]
已知和导图插件冲突，等待导图插件作者更新

**Comment by MystiKun** [comment]
好的，感谢
