### ISSUE TITLE
功能建议：主题适配编辑器

### ISSUE THREAD

**Issue by leipeng111** [HowcanoeWang/siyuan-plugin-background-cover#7]
插件很好，能帮助自定义想要的背景，现在双链弹出框、搜索框、设置界面背景没有覆盖，后续能覆盖就好了，看着统一一些

**Comment by HowcanoeWang** [comment]
最开始版本是覆盖的，但是图片选不好的话文字可读性很差，特地改成现在这样的。

后续版本会出一个主题css编辑器，可以自行编辑需要透明的部分，需要的话可以手动改一下

**Comment by jidenanian** [comment]
大佬，能不能增加一个根据图片api设置背景的功能。

**Comment by HowcanoeWang** [comment]
> 大佬，能不能增加一个根据图片api设置背景的功能。
> 

涉及到网络这一块太复杂了，有很多不确定性，之前那个自动题头图的插件这一块好像还没整出来呢，暂时只考虑本地的文件交互

**Comment by pyNpy** [comment]
很赞的一个功能，可以更改背景图片。
但发现存在一个问题，退出软件后，原先的图片会被清空 ，/public/siyuan-plugin-background-cover/assets/images 这个目录下的图片在每次重新启动后就会被清空，无法使用原先的图片，这是软件的问题，还是插件的问题？
如果是软件的问题，那么能使用其他目录能存储图片，而不会被清空么？

**Comment by HowcanoeWang** [comment]
启用css模式和主题编辑器，用body opacity实现统一覆盖

e27ece7d627616d292b56884dd3ee1158bd298ce
