### ISSUE TITLE
功能建议：支持日间与夜间模式下分别设置不同的背景

### ISSUE THREAD

**Issue by OriOYue** [HowcanoeWang/siyuan-plugin-background-cover#8]
功能建议：希望支持日间与夜间模式下分别设置不同的背景
毕竟日间模型下的背景在夜间模型下太伤眼睛了

还有就是希望支持一个模式（日间或夜间）可以设置背景图片，另一个（日间或夜间）支持关闭背景图片的设置，两个互不影响。
因为有些主题一个模式下自带的背景的也还不错，而另一个模式下就又有点不太如意。所以分开支持比较好。

感谢！

**Comment by HowcanoeWang** [comment]
背景图片和主题绑定感觉有点难整，因为和随机抽背景图这个功能冲突。

后续考虑给打开图片背景，支持设置屏蔽主题？

![image](https://github.com/HowcanoeWang/siyuan-plugin-background-cover/assets/19968935/eedc17f9-a99e-45e9-96e3-031065583869)

这个方案如何？

**Comment by OriOYue** [comment]
也行，毕竟我现在只需要设置light Blue主题，屏蔽dark blue刚刚好

**Comment by HowcanoeWang** [comment]
我大部分的图片在Savor的主题下都还行，有些主题实在是难适配也可能是一个问题。

目前暂时使用快捷键ctrl+shift+F4来快速开关吧
